---
sidebar: sidebar 
permalink: task_cli_upgrade_deploy.html 
keywords: administer, administering, cli, deploy, upgrade deploy 
summary: Sie können eine vorhandene virtuelle Maschine des Bereitstellungsdienstprogramms direkt über die Befehlszeilenschnittstelle aktualisieren. 
---
= Upgrade einer ONTAP Select Deploy-Instanz
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie können eine vorhandene virtuelle Maschine des Bereitstellungsdienstprogramms direkt über die Befehlszeilenschnittstelle aktualisieren.



== Bevor Sie beginnen

Stellen Sie sicher, dass Deploy während des Upgrades nicht für andere Aufgaben verwendet wird. Sie sollten die aktuellen Versionshinweise einsehen, um Informationen und Einschränkungen zum Upgrade des Deploy-Dienstprogramms zu erhalten.


NOTE: Wenn Sie eine ältere Instanz des ONTAP Select Deploy-Verwaltungsprogramms installiert haben, sollten Sie auf die aktuelle Version aktualisieren. Der ONTAP Select Knoten und die ONTAP Select Deploy-Komponente werden unabhängig voneinander aktualisiert. Siehe link:concept_adm_upgrading_nodes.html["Upgrade der ONTAP Select Knoten"^] für weitere Details.



== Laden Sie das Upgrade-Paket herunter

Um den Aktualisierungsprozess zu starten, müssen Sie die entsprechende Upgrade-Datei für die Deploy-virtuelle Maschine von der NetApp Support Site herunterladen. Das Upgrade-Paket ist als einzelne komprimierte Datei formatiert.

.Schritte
. Greifen Sie mit einem Webbrowser auf link:https://mysupport.netapp.com/site/["NetApp Support Site"^] zu und wählen Sie *Downloads* aus dem Menü Downloads.
. Scrollen Sie nach unten und wählen Sie *ONTAP Select Deploy Upgrade* aus.
. Wählen Sie die gewünschte Version des Upgrade-Pakets aus.
. Lesen Sie die Endbenutzer-Lizenzvereinbarung (EULA) und wählen Sie *Akzeptieren und fortfahren*.
. Wählen Sie das passende Paket aus und laden Sie es herunter, und beantworten Sie alle Eingabeaufforderungen entsprechend Ihrer Umgebung.




== Laden Sie das Paket auf die virtuelle Maschine Deploy hoch

Nach dem Erwerb des Upgrade-Pakets müssen Sie die Datei auf die Deploy-virtuelle Maschine hochladen.

.Bevor Sie beginnen
Sie müssen die Upgrade-Datei auf Ihrem lokalen Rechner verfügbar haben. Sie müssen außerdem das Passwort für das Administrator-Benutzerkonto haben.

.Über diese Tasks
In dieser Aufgabe wird eine Methode zum Hochladen der Datei auf die virtuelle Deploy-Maschine beschrieben. Möglicherweise gibt es andere Optionen, die für Ihre Umgebung besser geeignet sind.

.Schritte
. Verwenden Sie in einer Befehlsshell auf Ihrer lokalen Workstation das Dienstprogramm scp, um die Image-Datei auf die Deploy-virtuelle Maschine hochzuladen.
+
Beispiel

+
....
scp ONTAPdeploy2.12_upgrade.tar.gz admin@10.228.162.221:/home/admin (provide password when prompted)
....


.Ergebnis
Die Upgrade-Datei wird im Home-Verzeichnis des Administratorbenutzers gespeichert.



== Wenden Sie das Upgrade-Paket an

Nachdem die Upgrade-Datei auf die Deploy-virtuelle Maschine hochgeladen wurde, können Sie das Upgrade anwenden.

.Bevor Sie beginnen
Sie müssen wissen, in welchem Verzeichnis die Upgrade-Datei auf der Deploy Utility-VM abgelegt wurde. Stellen Sie außerdem sicher, dass Deploy während des Upgrades nicht für andere Aufgaben verwendet wird.

.Schritte
. Sign in mit dem Administratorkonto per SSH bei der CLI des Bereitstellungsdienstprogramms an.
. Führen Sie das Upgrade mit dem entsprechenden Verzeichnispfad und Dateinamen durch:
+
`deploy upgrade -package-path FILEPATH`

+
Beispiel

+
....
deploy upgrade -package-path /home/admin/ONTAPdeploy2.12_upgrade.tar.gz
....


.Nach Abschluss
Bevor das Upgrade-Verfahren abgeschlossen ist, werden Sie aufgefordert, eine Sicherung der Deploy-virtuellen Maschinenkonfiguration zu erstellen. Außerdem sollten Sie den Browser-Cache leeren, damit Sie die neu erstellten Deploy-Seiten anzeigen können.
